import "@/app/assets/globals.css";

import { Cormorant_Garamond, Jost } from "next/font/google";
const jost = Jost({
  subsets: ["latin"],
  weight: ["400"],
  display: "swap"
});
const cormo = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400","500"],
  display: "swap",
  variable: "--font-heading",
});

export const metadata = {
  title: "Iraboti Eco Resort",
  description: "Generated by create next app",
};
// custom
import NextTopLoader from "nextjs-toploader";
import { Theme_provider } from "@/components/providers/Theme_provider";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jost?.className} ${cormo?.variable}`}>
        <NextTopLoader
          color="#122223"
          // initialPosition={0.08}
          // crawlSpeed={200}
          // height={3}
          // crawl={true}
          showSpinner={false}
          // easing="ease"
          // speed={200}
          // shadow="0 0 10px #2299DD,0 0 5px #2299DD"
          //         template='<div class="bar" role="bar"><div class="peg"></div></div>
          // <div class="spinner" role="spinner"><div class="spinner-icon"></div></div>'
          // zIndex={1600}
          // showAtBottom={false}
        />

        <Theme_provider
          attribute="class"
          defaultTheme="light"
          // enableSystem
          // disableTransitionOnChange
        >
          {children}
        </Theme_provider>
      </body>
    </html>
  );
}
